# python version 
FROM python:3.9-slim

WORKDIR /app

COPY requirement.txt .

RUN pip install --no-cache-dir -r requirement.txt

COPY . .

EXPOSE 5000

ENV FLASK_APP=flaskmongo.py

CMD [ "flask","run","--host=0.0.0.0" ]
